<?php
/**
 * English Blog Data
 * =========================================
 * Add new posts at the TOP. They will appear first automatically
 * (sorted by 'published_at' date, newest first).
 */

$blogs = [
    [
        'slug'         => 'early-signs-of-heart-disease',
        'title'        => '7 Early Warning Signs of Heart Disease You Should Never Ignore',
        'excerpt'      => 'Heart disease often develops silently. Learn the subtle warning signs that could save your life and when to consult a cardiologist.',
        'content'      => '<p>Heart disease remains the leading cause of death worldwide, yet many people miss the early warning signs...</p><p>Common symptoms include chest discomfort, shortness of breath, fatigue, and irregular heartbeat...</p>',
        'image'        => 'https://images.pexels.com/photos/668300/pexels-photo-668300.jpeg?auto=compress&cs=tinysrgb&w=800',
        'author'       => 'Dr. Rajesh Kumar',
        'category'     => 'Cardiology',
        'tags'         => ['Heart Disease', 'Cardiology', 'Health Tips'],
        'read_time'    => '6 min read',
        'published_at' => '2026-06-01',
        'status'       => 'published',
    ],
    [
        'slug'         => 'managing-diabetes-daily',
        'title'        => 'Managing Diabetes: A Complete Daily Guide for Better Blood Sugar Control',
        'excerpt'      => 'Practical, evidence-based strategies to keep your blood sugar stable throughout the day and prevent long-term complications.',
        'content'      => '<p>Living with diabetes requires a balanced approach to diet, exercise, medication, and monitoring...</p>',
        'image'        => 'https://images.pexels.com/photos/7088489/pexels-photo-7088489.jpeg?auto=compress&cs=tinysrgb&w=800',
        'author'       => 'Dr. Priya Sharma',
        'category'     => 'Endocrinology',
        'tags'         => ['Diabetes', 'Lifestyle', 'Nutrition'],
        'read_time'    => '8 min read',
        'published_at' => '2026-05-28',
        'status'       => 'published',
    ],
    [
        'slug'         => 'knee-replacement-recovery',
        'title'        => 'Knee Replacement Recovery: What to Expect in the First 90 Days',
        'excerpt'      => 'A realistic timeline and expert advice for a smooth recovery after total knee replacement surgery.',
        'content'      => '<p>Recovery from knee replacement surgery is a journey that requires patience and dedication...</p>',
        'image'        => 'https://images.pexels.com/photos/7659564/pexels-photo-7659564.jpeg?auto=compress&cs=tinysrgb&w=800',
        'author'       => 'Dr. Amit Verma',
        'category'     => 'Orthopedics',
        'tags'         => ['Joint Replacement', 'Recovery', 'Surgery'],
        'read_time'    => '7 min read',
        'published_at' => '2026-05-22',
        'status'       => 'published',
    ],
    [
        'slug'         => 'child-nutrition-myths',
        'title'        => 'Top 10 Child Nutrition Myths Every Parent Should Stop Believing',
        'excerpt'      => 'From "force-feeding" to "no sugar at all" — our pediatricians debunk the most common nutrition myths for kids.',
        'content'      => '<p>Parents today are bombarded with nutrition advice from social media. Here is what science actually says...</p>',
        'image'        => 'https://images.pexels.com/photos/8460059/pexels-photo-8460059.jpeg?auto=compress&cs=tinysrgb&w=800',
        'author'       => 'Dr. Sneha Kapoor',
        'category'     => 'Pediatrics',
        'tags'         => ['Child Health', 'Nutrition', 'Parenting'],
        'read_time'    => '5 min read',
        'published_at' => '2026-05-15',
        'status'       => 'published',
    ],
    [
        'slug'         => 'understanding-migraine-triggers',
        'title'        => 'Understanding Migraine Triggers and How to Prevent Them Naturally',
        'excerpt'      => 'Migraines affect 1 in 7 people globally. Discover the most common triggers and evidence-backed prevention strategies.',
        'content'      => '<p>Migraines are more than just headaches. They are a complex neurological condition...</p>',
        'image'        => 'https://images.pexels.com/photos/3771115/pexels-photo-3771115.jpeg?auto=compress&cs=tinysrgb&w=800',
        'author'       => 'Dr. Vikram Singh',
        'category'     => 'Neurology',
        'tags'         => ['Migraine', 'Neurology', 'Headache'],
        'read_time'    => '6 min read',
        'published_at' => '2026-05-08',
        'status'       => 'published',
    ],
    [
        'slug'         => 'importance-of-regular-health-checkups',
        'title'        => 'Why Regular Health Checkups Are Your Best Defense Against Disease',
        'excerpt'      => 'Preventive healthcare saves lives. Learn which tests you need at every age and why skipping checkups is risky.',
        'content'      => '<p>Many serious conditions — high blood pressure, diabetes, certain cancers — develop without obvious symptoms...</p>',
        'image'        => 'https://images.pexels.com/photos/7088483/pexels-photo-7088483.jpeg?auto=compress&cs=tinysrgb&w=800',
        'author'       => 'Dr. Anil Mehta',
        'category'     => 'Preventive Care',
        'tags'         => ['Health Checkup', 'Prevention', 'Wellness'],
        'read_time'    => '5 min read',
        'published_at' => '2026-04-30',
        'status'       => 'published',
    ],
    [
        'slug'         => 'pregnancy-care-first-trimester',
        'title'        => 'First Trimester Pregnancy Care: A Week-by-Week Guide for Moms-to-Be',
        'excerpt'      => 'The first 12 weeks are crucial. Essential tips on diet, exercise, screenings, and what to expect during early pregnancy.',
        'content'      => '<p>Discovering you are pregnant is the beginning of an incredible journey. The first trimester sets the foundation...</p>',
        'image'        => 'https://images.pexels.com/photos/1556652/pexels-photo-1556652.jpeg?auto=compress&cs=tinysrgb&w=800',
        'author'       => 'Dr. Neha Gupta',
        'category'     => 'Obstetrics & Gynecology',
        'tags'         => ['Pregnancy', 'Women Health', 'Maternity'],
        'read_time'    => '9 min read',
        'published_at' => '2026-04-22',
        'status'       => 'published',
    ],
    [
        'slug'         => 'kidney-stones-prevention',
        'title'        => 'Kidney Stones: Causes, Symptoms, and How to Prevent Them',
        'excerpt'      => 'Kidney stones are increasingly common. Learn what causes them, how to recognize the symptoms, and simple prevention tips.',
        'content'      => '<p>Kidney stones affect 1 in 10 people at some point in their lives. The good news: most are preventable...</p>',
        'image'        => 'https://images.pexels.com/photos/4386466/pexels-photo-4386466.jpeg?auto=compress&cs=tinysrgb&w=800',
        'author'       => 'Dr. Sanjay Roy',
        'category'     => 'Nephrology',
        'tags'         => ['Kidney Health', 'Nephrology', 'Hydration'],
        'read_time'    => '6 min read',
        'published_at' => '2026-04-15',
        'status'       => 'published',
    ],
    [
        'slug'         => 'mental-health-after-40',
        'title'        => 'Mental Health After 40: Breaking the Stigma Around Aging and Wellbeing',
        'excerpt'      => 'Mental health is just as important as physical health. Here is how to recognize signs of depression and anxiety in midlife.',
        'content'      => '<p>Mental health challenges in middle age are more common than people think. Recognizing the signs early can change lives...</p>',
        'image'        => 'https://images.pexels.com/photos/3771069/pexels-photo-3771069.jpeg?auto=compress&cs=tinysrgb&w=800',
        'author'       => 'Dr. Kavita Joshi',
        'category'     => 'Mental Health',
        'tags'         => ['Mental Health', 'Wellbeing', 'Aging'],
        'read_time'    => '7 min read',
        'published_at' => '2026-04-08',
        'status'       => 'published',
    ],
];
